apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-vault-reader
  namespace: mongodb
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: mongodb-vault
  namespace: mongodb
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mongodb-vault-auth
  namespace: mongodb
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: mongodb-vault
  kubernetes:
    role: mongodb-reader
    serviceAccount: mongodb-vault-reader
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongodb-auth-from-vault
  namespace: mongodb
spec:
  vaultAuthRef: mongodb-vault-auth
  mount: secret
  type: kv-v2
  path: mongodb/auth
  refreshAfter: 60s
  destination:
    create: true
    overwrite: true
    name: mongodb-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongodb-internal-auth-from-vault
  namespace: mongodb
spec:
  vaultAuthRef: mongodb-vault-auth
  mount: secret
  type: kv-v2
  path: mongodb/internal-auth
  refreshAfter: 60s
  destination:
    create: true
    overwrite: true
    name: mongodb-internal-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongo-0-tls-from-vault
  namespace: mongodb
spec:
  vaultAuthRef: mongodb-vault-auth
  mount: secret
  type: kv-v2
  path: mongodb/tls/mongo-0
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: StatefulSet
      name: mongodb
  destination:
    create: true
    overwrite: true
    name: mongo-0-tls
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongo-1-tls-from-vault
  namespace: mongodb
spec:
  vaultAuthRef: mongodb-vault-auth
  mount: secret
  type: kv-v2
  path: mongodb/tls/mongo-1
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: StatefulSet
      name: mongodb
  destination:
    create: true
    overwrite: true
    name: mongo-1-tls
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongo-2-tls-from-vault
  namespace: mongodb
spec:
  vaultAuthRef: mongodb-vault-auth
  mount: secret
  type: kv-v2
  path: mongodb/tls/mongo-2
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: StatefulSet
      name: mongodb
  destination:
    create: true
    overwrite: true
    name: mongo-2-tls
